name: marsvision

channels:
  - pytorch
  - defaults

dependencies:
  - pytorch
  - torchvision
  - cudatoolkit

pip:
  - coveralls: 3.3.1
  - exif: 1.3.5
  - matplotlib: 3.2.2
  - mypy: 0.981
  - mypy-extensions: 0.4.3
  - numpy: 1.21.6
  - opencv-python: 4.6.0.66
  - pandas: 1.35
  - pandas-datareader: 0.9.0
  - pandas-gbq: 0.13.3
  - pandas-profiling: 1.4.1
  - pdsc: 1.4.1
  - Pillow: 7.1.2
  - pytorch-sphinx-theme: 0.0.19
  - pytest: 3.6.4
  - pytest-cov: 2.9.0
  - Sphinx: 1.8.6
  - scikit-learn: 1.0.2
  - scipy: 1.7.3
  - tensorboard: 2.8.0